export const API_BASE_URL = "https://api.scryfall.com"

export const CARD_BACK_URI = "https://www.frogtown.me/images/gatherer/CardBack.jpg"

export const TOKEN_CARD_BACK_URI = "https://cdn.discordapp.com/attachments/253343722568286208/665323928318640143/-553-hr.png"

export const BOOSTER_ARTS = {
    akh: ['https://i.imgur.com/zRDZwGG.png', 'https://i.imgur.com/ncSkUsA.png', 'https://i.imgur.com/4VZ3eMo.png', 'https://i.imgur.com/EKGdzCj.png', 'https://i.imgur.com/UzDRDVi.png'],
    hou: ['https://i.imgur.com/uztmaPP.png', 'https://i.imgur.com/boVNhYi.png', 'https://i.imgur.com/AsNZMIV.png', 'https://i.imgur.com/QAZX0xz.png', 'https://i.imgur.com/nc7btWJ.png'],
    mh1: ['https://i.imgur.com/hNfRvap.png', 'https://i.imgur.com/R5nyVbP.png', 'https://i.imgur.com/Utpizyw.png'],
    xln: ['https://i.imgur.com/WsJPATh.png', 'https://i.imgur.com/do2BqoI.png', 'https://i.imgur.com/CUcLydg.png', 'https://i.imgur.com/qlQtwed.png', 'https://i.imgur.com/LGoIHEY.png'],
    ori: ['https://i.imgur.com/hdl2H9H.png', 'https://i.imgur.com/2kLcfPP.png', 'https://i.imgur.com/HZwN91m.png', 'https://i.imgur.com/jy6pCnl.png', 'https://i.imgur.com/QnZtGkN.png'],
    rna: ['https://i.imgur.com/GHHeI6R.png', 'https://i.imgur.com/O7RoNp5.png', 'https://i.imgur.com/6CvahgS.png', 'https://i.imgur.com/h2sRj1Z.png', 'https://i.imgur.com/9Tm3CEK.png'],
    eld: ['https://i.imgur.com/bqr43HV.png', 'https://i.imgur.com/otbxevD.png', 'https://i.imgur.com/03ZroWf.png', 'https://i.imgur.com/SQmj2BS.png'],
    grn: ['https://i.imgur.com/zHqy7l8.png', 'https://i.imgur.com/RtLE0ng.png', 'https://i.imgur.com/CcYnkb0.png', 'https://i.imgur.com/7bREzIS.png', 'https://i.imgur.com/V6vg9Ug.png'],
    ima: ['https://i.imgur.com/0nfeblM.png', 'https://i.imgur.com/tIm2jTD.png', 'https://i.imgur.com/ntznvcc.png'],
    'm19': ['https://i.imgur.com/g4dbP33.png', 'https://i.imgur.com/k7Pnj9Y.png', 'https://i.imgur.com/fsJdBka.png', 'https://i.imgur.com/RChV4K7.png', 'https://i.imgur.com/8NoSxqx.png'],
    'm20': ['https://i.imgur.com/77ARwIX.png', 'https://i.imgur.com/hyCjZMf.png', 'https://i.imgur.com/PQD3Fqo.png'],
    rix: ['https://i.imgur.com/35BocsF.png', 'https://i.imgur.com/Gyrw3Q7.png', 'https://i.imgur.com/Yge9IXU.png', 'https://i.imgur.com/ihYcp28.png', 'https://i.imgur.com/7NOrSNK.png'],
    thb: ['https://i.imgur.com/snBnMFI.png', 'https://i.imgur.com/kmNNFth.png', 'https://i.imgur.com/tv6VFyV.png'],
    uma: ['https://i.imgur.com/hTjwyKf.png', 'https://i.imgur.com/fJBacJZ.png', 'https://i.imgur.com/Z5P0JxT.png'],
    war: ['https://i.imgur.com/jCAvsPj.png', 'https://i.imgur.com/o0YXi73.png', 'https://i.imgur.com/ZbuweF6.png'],
    dom: ['https://i.imgur.com/L780xGw.png', 'https://i.imgur.com/vmxVsOV.png', 'https://i.imgur.com/yqPhsht.png', 'https://i.imgur.com/yEcnviG.png', 'https://i.imgur.com/EzQfURU.png'],
    'mm3': ['https://i.imgur.com/1CRzzFv.png', 'https://i.imgur.com/GHh8ZpS.png'],
    bbd: ['https://i.imgur.com/EidtjcP.jpg', 'https://i.imgur.com/veup7uh.jpg', 'https://i.imgur.com/t2PhmkS.jpg'],
    ogw: ['https://i.imgur.com/DypxOSz.jpg', 'https://i.imgur.com/vJ5NgV9.jpg', 'https://i.imgur.com/BJb3zJb.jpg', 'https://i.imgur.com/bKuby0K.jpg'],
    default: ['https://i.imgur.com/9YaMle6.png'],
    arn: ['https://i.imgur.com/G0iGZel.png'],
    atq: ['https://i.imgur.com/oID833g.png'],
    leg: ['https://i.imgur.com/ve2LRFH.png'],
    fem: ['https://i.imgur.com/vJJX0V1.png'],
    chr: ['https://i.imgur.com/vFJgCFL.png', 'https://i.imgur.com/8pt82QN.png'],
    hml: ['https://i.imgur.com/lXcUsE9.png'],
    ice: [ 'https://i.imgur.com/6pDbvqF.png' ],
    all: ['https://i.imgur.com/sNCT19S.png', 'https://i.imgur.com/5lstZ1k.png'],
    mir: ['https://i.imgur.com/hYkPLYv.png', 'https://i.imgur.com/haiNaiT.png'],
    vis: ['https://i.imgur.com/2c8ZJMd.png', 'https://i.imgur.com/cMFKJxz.png'],
    '5ed': [ 'https://i.imgur.com/DXIUXkx.png'],
    wth: ['https://i.imgur.com/z7jGccP.png'],
    '4ed': ['https://i.imgur.com/QMXwqqq.png'],
    '4bb': ['https://i.imgur.com/QMXwqqq.png'],
    tmp: [ 'https://i.imgur.com/7j8EY2c.png'],
    tpr: [ 'https://i.imgur.com/7j8EY2c.png'],
    sth: ['https://i.imgur.com/ENrMIap.png', 'https://i.imgur.com/lfagkyV.png'],
    exo: ['https://i.imgur.com/doD7FkY.png', 'https://i.imgur.com/LuIPM8C.png'],
    usg: ['https://i.imgur.com/X76vlYI.png', 'https://i.imgur.com/qIbKhLN.png'],
    ulg: ['https://i.imgur.com/GOyATzM.png', 'https://i.imgur.com/dj9Xubw.png'],
    '6ed': ['https://i.imgur.com/YXyV7rQ.png'],
    uds: ['https://i.imgur.com/j37rVsZ.png', 'https://i.imgur.com/jh8ZV5D.png'],
    mmq: ['https://i.imgur.com/so798zB.png', 'https://i.imgur.com/8hAAuJi.png'],
    nem: ['https://i.imgur.com/HVL7Pmq.png', 'https://i.imgur.com/17SUYn9.png'],
    pcy: ['https://i.imgur.com/l0okG7i.png'],
    inv: ['https://i.imgur.com/UCzk555.png'],
    pls: ['https://i.imgur.com/vOeHtOx.png'],
    '7ed': ['https://i.imgur.com/mLkOkxp.png'],
    apc: ['https://i.imgur.com/I0w1mNk.png'],
    ody: ['https://i.imgur.com/JYdDxTd.png'],
    tor: ['https://i.imgur.com/dgeNT4k.png'],
    ons: ['https://i.imgur.com/OfJnY0V.png'],
    lgn: ['https://i.imgur.com/s4Z3ejK.png'],
    scg: ['https://i.imgur.com/DYYJY9G.png'],
    mrd: ['https://i.imgur.com/44tCwNL.png'],
    dst: ['https://i.imgur.com/7HdNQZh.png', 'https://i.imgur.com/cEZ1GYt.png'],
    '5dn': ['https://i.imgur.com/4t7Zkzv.png'],
    chk: ['https://i.imgur.com/cUPitGJ.png'],
    bok: ['https://i.imgur.com/B2YqwJ9.png'],
    sok: ['https://i.imgur.com/shO7Sl0.png'],
    rav: ['https://i.imgur.com/SvgVCSo.png'],
    gpt: ['https://i.imgur.com/LkRyu11.png'],
    dis: ['https://i.imgur.com/eKQA6Ix.png'],
    '9ed': ['https://i.imgur.com/nWMjula.png'],
    '8ed': ['https://i.imgur.com/U46t0yA.png'],
    isd: ['https://i.imgur.com/hAAwQxd.png', 'https://i.imgur.com/HcCfNKW.png', 'https://i.imgur.com/WMA5D6s.png', 'https://i.imgur.com/QlkCQLk.png', 'https://i.imgur.com/1avTnCL.png', 'https://i.imgur.com/2Urc70W.png'],
    m13: ['https://i.imgur.com/SUr5GMN.png', 'https://i.imgur.com/ielrQvD.png', 'https://i.imgur.com/VBzyV42.png', 'https://i.imgur.com/vhwWona.png', 'https://i.imgur.com/gdWGsMl.png', 'https://i.imgur.com/4dfA0I4.png'],
    nph: ['https://i.imgur.com/XZAJfYT.jpg', 'https://i.imgur.com/XuRwe2A.jpg', 'https://i.imgur.com/6TZQ0fG.jpg'],
    arb: ['https://i.imgur.com/e8M4DKx.png'],
    m14: ['https://i.imgur.com/k86UPqr.png', 'https://i.imgur.com/FNT6zoY.png', 'https://i.imgur.com/tb9dO2Z.png'],
    bng: ['https://i.imgur.com/sXeN6i8.png', 'https://i.imgur.com/WeXnsEx.png'],
    dka: ['https://i.imgur.com/Jx7pAG8.png', 'https://i.imgur.com/cUpvV5o.png', 'https://i.imgur.com/h4AlHQC.png'],
    dtk: ['https://i.imgur.com/EMF3Le6.png'],
    eve: ['https://i.imgur.com/VtRPTKK.png'],
    frf: ['https://i.imgur.com/45ECZCz.jpg'],
    fut: ['https://i.imgur.com/oqjslhO.png', 'https://i.imgur.com/gZGs4Q0.png'],
    gtc: ['https://i.imgur.com/rcNmHBc.png', 'https://i.imgur.com/9P7NiDu.png', 'https://i.imgur.com/pUieP0R.png'],
    jou: ['https://i.imgur.com/2Yks73I.png', 'https://i.imgur.com/zFNXaqN.png'],
    jud: ['https://i.imgur.com/8zYCSRo.png'],
    ktk: ['https://i.imgur.com/jt1AL4N.png'],
    m15: ['https://i.imgur.com/2xJGPkh.png', 'https://i.imgur.com/Ijpfsve.png', 'https://i.imgur.com/CCkFAfE.png', 'https://i.imgur.com/KB1KhAM.png', 'https://i.imgur.com/MgntHe4.png'],
    lrw: ['https://i.imgur.com/gvXAbeB.png'],
    mbs: ['https://i.imgur.com/R2UFJWs.png'],
    mor: ['https://i.imgur.com/HbUDC84.png'],
    avr: ['https://i.imgur.com/cNCdynh.png', 'https://i.imgur.com/8ysrdRH.png', 'https://i.imgur.com/HsEmY6M.png', 'https://i.imgur.com/AvJMwk6.png', 'https://i.imgur.com/KTtBq6h.png'],
    '10e': ['https://i.imgur.com/evqNfOM.png', 'https://i.imgur.com/cypqeju.png' ],
    m10: ['https://i.imgur.com/YRnOQqS.png'],
    m11: ['https://i.imgur.com/2mKTKBc.png', 'https://i.imgur.com/5LvEt7n.png', 'https://i.imgur.com/bDKtZor.png', 'https://i.imgur.com/bv7xIKw.png'],
    con: ['https://i.imgur.com/IkVja90.png'],
    m12: ['https://i.imgur.com/LEDMCYK.png'],
    dgm: ['https://i.imgur.com/DXQK42m.png', 'https://i.imgur.com/Kb0YP1k.png', 'https://i.imgur.com/ddXq6Lk.png'],
    roe: ['https://i.imgur.com/tznKgSD.png'],
    som: ['https://i.imgur.com/RZB8VPc.png', 'https://i.imgur.com/B67QoED.png', 'https://i.imgur.com/POPzp8T.png', 'https://i.imgur.com/OfHyoJa.png', 'https://i.imgur.com/UFZ9z2F.png'],
    ths: ['https://i.imgur.com/CHS0PE4.png', 'https://i.imgur.com/M59VwAY.png', 'https://i.imgur.com/Rfzrigd.png', 'https://i.imgur.com/tkLLNdD.png', 'https://i.imgur.com/V8nc09k.png'],
    wwk: ['https://i.imgur.com/yfMh1sh.png'],
    plc: ['https://i.imgur.com/KyNONlq.jpg', 'https://i.imgur.com/NKaFvWj.png'],
    rtr: ['https://i.imgur.com/DcwDjBm.jpg', 'https://i.imgur.com/dVpZ6kb.png', 'https://i.imgur.com/DzKcjyL.png', 'https://i.imgur.com/VV8iqst.png'],
    shm: ['https://i.imgur.com/bgcEu0p.png'],
    ala: ['https://i.imgur.com/TpxbBoe.png'],
    tsp: ['https://i.imgur.com/BzJVQXY.png'],
    zen: ['https://i.imgur.com/muTfcLJ.png'],
    lea: ['https://i.imgur.com/Mj38OXm.png'],
    drk: ['https://i.imgur.com/RLk1RQx.png'],
    bfz: ['https://i.imgur.com/zw3PLOz.png']

    
    
}; 